[build]
  ignore = "/bin/false"
  base = ".markpub"
  publish = "./output"
  command = "markpub build -i .. -o ./output -t ./this-website-themes/sk-dolce --lunr --commits"

[build.environment]
  PYTHON_VERSION = "3.12"
